services:

  server-api:
        container_name: golden.raspberry.awards.server
        build:
            context: .
            dockerfile: src/Services.Api/Dockerfile
        ports:
            - "8080:8080"
        environment:
            - TZ=America/Sao_Paulo
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
        